"""Add Module 2 medication safety tables

Revision ID: ac2fe91fc0f3
Revises: 67fb65aafeee
Create Date: 2026-08-27 15:26:20.567765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac2fe91fc0f3'
down_revision: Union[str, Sequence[str], None] = '67fb65aafeee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug_concepts',
    sa.Column('rxcui', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('tty', sa.String(length=20), nullable=True),
    sa.Column('synonym', sa.String(length=500), nullable=True),
    sa.Column('is_branded', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('rxcui')
    )
    op.create_index('ix_drug_concepts_name', 'drug_concepts', ['name'], unique=False)
    op.create_index('ix_drug_concepts_refreshed_at', 'drug_concepts', ['refreshed_at'], unique=False)
    op.create_table('external_api_cache',
    sa.Column('cache_key', sa.String(length=500), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_index('ix_external_api_cache_fetched_at', 'external_api_cache', ['fetched_at'], unique=False)
    op.create_table('ingredient_limits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ingredient_key', sa.String(length=255), nullable=False),
    sa.Column('ingredient_name', sa.String(length=255), nullable=False),
    sa.Column('max_daily_mg', sa.Float(), nullable=True),
    sa.Column('audience', sa.String(length=50), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_label_id', sa.String(length=100), nullable=True),
    sa.Column('label_excerpt', sa.Text(), nullable=True),
    sa.Column('caution_note', sa.Text(), nullable=True),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_daily_mg IS NULL OR max_daily_mg > 0', name='ck_ingredient_limit_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_key')
    )
    op.create_index('ix_ingredient_limits_key', 'ingredient_limits', ['ingredient_key'], unique=False)
    op.create_table('drug_ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rxcui', sa.String(length=20), nullable=False),
    sa.Column('ingredient_rxcui', sa.String(length=20), nullable=True),
    sa.Column('ingredient_name', sa.String(length=255), nullable=False),
    sa.Column('ingredient_key', sa.String(length=255), nullable=False),
    sa.Column('strength_amount', sa.Float(), nullable=True),
    sa.Column('strength_unit', sa.String(length=20), nullable=True),
    sa.Column('strength_mg', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['rxcui'], ['drug_concepts.rxcui'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rxcui', 'ingredient_rxcui', name='uq_drug_ingredient_pair')
    )
    op.create_index('ix_drug_ingredients_ingredient_key', 'drug_ingredients', ['ingredient_key'], unique=False)
    op.create_table('safety_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('medication_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('findings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('severity_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('highest_severity', sa.Enum('none', 'info', 'moderate', 'high', name='safety_severity'), nullable=False),
    sa.Column('sources_used', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('rule_engine_version', sa.String(length=50), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_safety_checks_user_created', 'safety_checks', ['user_id', 'created_at'], unique=False)
    op.create_table('user_medications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rxcui', sa.String(length=20), nullable=True),
    sa.Column('display_name', sa.String(length=500), nullable=False),
    sa.Column('units_per_dose', sa.Float(), nullable=False),
    sa.Column('doses_per_day', sa.Float(), nullable=False),
    sa.Column('schedule_note', sa.String(length=255), nullable=True),
    sa.Column('entry_source', sa.Enum('search', 'manual', 'barcode', 'ocr', name='medication_entry_source'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('doses_per_day IS NULL OR doses_per_day > 0', name='ck_user_med_doses_positive'),
    sa.CheckConstraint('units_per_dose IS NULL OR units_per_dose > 0', name='ck_user_med_units_positive'),
    sa.ForeignKeyConstraint(['rxcui'], ['drug_concepts.rxcui'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_medications_user_active', 'user_medications', ['user_id', 'is_active'], unique=False)
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(length=500), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'name')
    op.drop_index('ix_user_medications_user_active', table_name='user_medications')
    op.drop_table('user_medications')
    op.drop_index('ix_safety_checks_user_created', table_name='safety_checks')
    op.drop_table('safety_checks')
    op.drop_index('ix_drug_ingredients_ingredient_key', table_name='drug_ingredients')
    op.drop_table('drug_ingredients')
    op.drop_index('ix_ingredient_limits_key', table_name='ingredient_limits')
    op.drop_table('ingredient_limits')
    op.drop_index('ix_external_api_cache_fetched_at', table_name='external_api_cache')
    op.drop_table('external_api_cache')
    op.drop_index('ix_drug_concepts_refreshed_at', table_name='drug_concepts')
    op.drop_index('ix_drug_concepts_name', table_name='drug_concepts')
    op.drop_table('drug_concepts')
    # ### end Alembic commands ###
